### ISSUE TITLE
a difference between the code and the paper about Frangi Filter

### ISSUE THREAD

**Issue by Jane007-GUO** [aelefebv/nellie#19]
I found a difference between the code and the paper about Frangi Filter in line 169 of nellie\segmentetion\filtering.py 

![1713948410459](https://github.com/aelefebv/nellie/assets/59250873/fdd1f119-cff6-4688-ae2d-b7913635a70d)

in the paper rb_sq=(abs(λ1)/sqrt(abs(λ2)abs(λ3)))**2,  but in the code the numerator is λ2, i wonder if it's a mistake or the author has some other considerations.

Thanks~

**Comment by aelefebv** [comment]
So, I've just run the validation studies, and it turns out keeping the second largest eigenvalue as the numerator marginally improves f1 and IoU of objects of different sizes and intensities. This actually makes sense since this deemphasizes purely linear structures and balances it for detection towards both linear and blob-like structures.
It is now officially a feature, and not a bug.
Thanks again for pointing this out!

**Comment by Jane007-GUO** [comment]
It's really interesting and also gives me some inspiration for designing structural response functions. 
I am glad to be of help and wish you all the best in your work : )
